version: "3.8"
services:
  database:
    image: postgres
    restart: always
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: